### ISSUE TITLE
Uncaught TypeError: marker.destroy is not a function

### ISSUE THREAD

**Issue by bogdanRada** [Peekmo/atom-autocomplete-php#108] opened 2015-09-23 06:56 UTC
[Enter steps to reproduce below:]

1. Open Atom
2. Open a Ruby file or Gemfile and see the error
3. Upon making any changes to the file, the error keeps coming up 

**Atom Version**: 1.0.15
**System**: Ubuntu 15.04
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.10.7

### Stack Trace

Uncaught TypeError: marker.destroy is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:809

TypeError: marker.destroy is not a function
  at GotoFunction.module.exports.GotoFunction.cleanMarkers (/home/raul/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:265:20)
  at /home/raul/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:34:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:35.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.1.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:19.7.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:16.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:15.2.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:15.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:paste (atom-text-editor.editor.is-focused)
  7x -0:04.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view-git-modified"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.18
atom-autocomplete-php, v0.10.7
atom-beautify, v0.28.12
atom-eco, v0.2.0
atom-erb, v0.2.0
atom-everydayrails-rspec, v0.2.0
atom-html-preview, v0.1.11
atom-shortcuts, v0.0.2
atom-snippets, v0.1.1
atom-text-transformer, v0.7.0
atomatigit, v1.5.4
auto-indent, v0.5.0
autocomplete-ctags, v0.3.1
autocomplete-emojis, v2.2.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-plus-python-jedi, v0.3.6
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
autosave-plus, v0.5.2
badges, v2.0.3
bootstrap-3-snippetset, v0.0.6
bootstrap3-snippets, v0.1.2
build-markdown, v1.0.2
color-picker, v2.0.12
default-language, v0.2.0
file-icons, v1.6.9
git-diff-details, v0.20.0
git-go, v1.0.1
git-log, v0.4.1
github-utils, v0.6.2
jshint, v1.8.0
jsonlint, v1.1.2
language-diff, v0.3.1
language-dots, v0.0.4
language-ejs, v0.2.0
language-mongodb, v0.2.0
language-sas, v0.2.4
line-diff-details, v1.1.2
linter, v1.6.0
linter-9e-sass, v0.5.0
linter-ansible-lint, v0.0.7
linter-bootlint, v0.0.6
linter-csslint, v1.0.5
linter-doiuse, v0.2.3
linter-erb, v0.1.1
linter-flint, v0.1.1
linter-flow, v3.1.0
linter-gcc, v0.3.8
linter-haml, v1.0.0
linter-hlint, v0.4.2
linter-jscs, v3.0.0
linter-markdown, v1.2.1
linter-markdownlint, v1.0.1
linter-php, v1.0.3
linter-rubocop, v0.3.4
linter-ruby, v1.1.1
linter-ruby-reek, v1.3.0
linter-scss-lint, v2.0.0
linter-scss-lint-caseywebdev, v2.0.2
linter-squirrel, v0.3.0
linter-stylelint, v1.0.6
linter-xmllint, v0.0.7
markdown-format, v2.5.1
markdown-preview-plus, v2.1.1
markdown-table-formatter, v2.5.3
node-debugger, v1.1.8
php-debug, v0.1.3
pigments, v0.15.0
rails-i18n, v0.1.3
recent-projects, v0.8.8
ruby-block, v0.3.5
ruby-define-method, v0.2.2
ruby-slim, v0.2.0
sinatra-snippets, v1.4.0
symbols-tree-view, v0.10.0
tab-length, v0.1.0
tabs-to-spaces, v0.11.1
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.2.1

# Dev
No dev packages
```

**Comment by hotoiledgoblinsack** [comment] 2015-10-08 16:16
@bogdanRada Is this still a problem? I can't immediately reproduce this.

**Comment by Peekmo** [comment] 2015-10-08 19:16
As many things changed since this issue, I'm closing it. Open a new one if the problem occurs (with more informations on how reproducing it please).

**Closed by Peekmo** 2015-10-08 19:16 UTC
Labels: bug

**Comment by bogdanRada** [comment] 2015-10-09 06:48
this only happens when pressing CTRL+S from keyboard to save a ruby file.

**Comment by Peekmo** [comment] 2015-10-09 07:07
You always have it ? Cause I tried many times, and I haven't got the error :(
Your ruby file is opened in the same window as PHP file ?

**Comment by bogdanRada** [comment] 2015-10-09 10:59
yes, it is opened in same window but different tab

**Comment by hannesbe** [comment] 2015-10-18 00:18
same here, even when no PHP files open, using CTRL+S saving any file
