### ISSUE TITLE
Some tooltips won't disappear

### ISSUE THREAD

**Issue by luishdez** [Peekmo/atom-autocomplete-php#107] opened 2015-09-22 20:28 UTC
It's happening since last update

![tooltips](https://cloud.githubusercontent.com/assets/38347/10030669/2fba86f0-6179-11e5-930a-464f458e3619.png)

**Comment by Peekmo** [comment] 2015-09-23 05:42
I get this bug once yesterday too.

@hotoiledgoblinsack could it be from this PR : https://github.com/Peekmo/atom-autocomplete-php/pull/92 ?

**Comment by hotoiledgoblinsack** [comment] 2015-09-23 15:30
It could, but it would be strange as that pull request only added the tooltips on the annotations and didn't change the logic of the original tooltips. I hadn't noticed this yet, but I did have tooltips coming up at the wrong locations sometimes. I'll try to take a look at it.

**Comment by Peekmo** [comment] 2015-09-23 15:36
I agree.
Perhaps that's an older bug, I just had it one time yesterday, I didn't reproduce it today. So.. Really hard to debug.

**Comment by luishdez** [comment] 2015-09-23 16:57
May be these gifs help. 

It happens to me a lot. Once they show a duplicated tooltip things start to get messy. duplicated tooltips, misplaced etc

![duplicated](https://cloud.githubusercontent.com/assets/38347/10051960/7321162e-6224-11e5-9ae4-1b0f374ced2b.gif)
![misplaced](https://cloud.githubusercontent.com/assets/38347/10051962/74b84c1e-6224-11e5-9b9b-b5001f2b9a95.gif)

**Comment by Peekmo** [comment] 2015-09-23 17:30
Oh yes thank you.

In fact, to reproduce the bug : 
- Get the tooltip
- Move the cursor (with keyboard at least) till the editor is scrolling
- tadaaaam

**Comment by hotoiledgoblinsack** [comment] 2015-09-23 19:00
I can reproduce it and I've been tinkering with the code, but I'm starting to wonder if this is something we can actually fix. As far as I understand it, tooltips are attached to elements, so the normal mode of operation is:
  * Attach tooltip to element once somewhere, e.g. when the editor is first opened.
  * Whenever the user hovers over the element, the tooltip will be automatically displayed and hidden when the mouse leaves the element. This does not require programmer intervention and is handled by Atom.

We're more or less 'abusing' tooltips by registering one with the documentation as content when the mouse goes over the element. At that point the tooltip is just registered for the element being hovered on, but it is not necessarily displayed (***this is probably also why tooltips don't show up immediately***). When the mouse moves out again, we dispose the tooltip. At that point, the tooltip is no longer attached to the element, but it doesn't force close or hide it if it is already showing, it merely tells atom to stop letting a tooltip pop up whenever the mouse goes over the element. In short, we're not managing the visibility of the tooltips in our code, we're managing their attachment.

If this is correct, this leaves us with the question of how we will fix this issue. I see the following options:
  * We register all tooltips for each element when the editor is opened. We could clear and reattach them when the editor is saved (like the annotations do). This *could* be a performance hit, but I'd need to try it out to be certain. Also, if one editor is showing documentation of a method from another editor, updating the docblock in the second editor will not update the documentation in the first editor (or we'd need to clear/reattach all markers in all open files for each save).
  * We keep working the way we do, with mousemove and mouseout events, but we don't use atom's tooltip anymore and style a custom tooltip.

@Peekmo What do you think?

**Comment by Peekmo** [comment] 2015-09-23 19:35
Perhaps an issue with atom so ?

Anyway, from your 2 options, I prefer the second one (even if it's a lot harder to code that) for 2 reasons : 
- Less things in memory (really important as you know, the plugin had some performance issues at its first times^^)
- The ability to use this tooltip creator everywhere in the plugin. Today just mouse moves can add a tooltip, I tried to add a keyboard shortcut, I never succeed because I never found a way to find what is the shadow dom element under the current cursor. With a manually created tooltip, we could handle this case easily in my opinion.

Unfortunately, we will lose the style. We will have to try to get the existing CSS classes.

**Comment by hotoiledgoblinsack** [comment] 2015-09-23 20:05
I was thinking the same thing. Perhaps we can somehow have our tooltip extend the style of the standard tooltip.

At first I also thought it was a bug in Atom, but now I'm starting to think it's in fact intended behavior; I think tooltips were never meant for displaying and hiding on demand, which is probably why someone had the idea of implementing the popovers, which essentially does what I originally thought tooltips were for ;-). It's aim is also to prevent different packages from doing their own implementation, which we are considering right this very moment :P.

**Comment by Peekmo** [comment] 2015-09-29 07:10
Fix by #126

**Comment by Thijzer** [comment] 2015-09-29 09:12
Hi, version 1.3.0 did not fix floating tooltip issue. :(


![tinygrab screen shot 29-09-15 11 08 03](https://cloud.githubusercontent.com/assets/3798321/10159796/dbff3660-669a-11e5-8422-54fc96bb80e6.png)

**Comment by Peekmo** [comment] 2015-09-29 09:29
Humm, weird, I do not reproduce it.

**Comment by Peekmo** [comment] 2015-09-29 09:30
It sticks when you scroll, but when you're mouse has moved, it shoud not stick on the screen ?

**Comment by hotoiledgoblinsack** [comment] 2015-09-29 11:07
That's right, no mouseout event is generated when scrolling without moving the mouse (until the mouse is moved again).

**Comment by Peekmo** [comment] 2015-09-29 11:57
if @Thijzer confirms that it disappear after scroll, I will reclose this issue, 'cause it's acceptable ;)

**Comment by Thijzer** [comment] 2015-09-29 13:43
It was sticking to all the windows in buffer. Scrolling nor clicking helped removing the tooltip.
Had to close the atom to remove it.

I'll enable the plugin agian with v13.1 to see if I can actually reproduce this bug again.

**Comment by hotoiledgoblinsack** [comment] 2015-09-29 15:06
I've also had this happen sometimes, but not only with this plugin's tooltips, also with tooltips in other locations (such as the cursor location tooltip in the status bar or the tab tooltip).

What you can do instead of restarting Atom is open the inspector (Ctrl+Shift+I) and look for element html > body > div.tooltip (usually the last div in the body element) and remove it (delete key).

**Comment by Thijzer** [comment] 2015-09-30 11:51
I have been working on v13.1 and can't seem to replicate the issue. 
So I would recommend closing the issue for now. 
If the issue would recur I'll comment back here with a better documented anaylises.

**Comment by Peekmo** [comment] 2015-09-30 11:54
Ok, thank you ;)

**Closed by Peekmo** 2015-09-30 11:54 UTC
Labels: bug

**Comment by KEIII** [comment] 2015-11-22 13:46
If goto marker is in same file but need scroll, after goto tooltip won't disappear.
