### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by rdcklinux** [Peekmo/atom-autocomplete-php#39] opened 2015-07-22 16:15 UTC
[Enter steps to reproduce below:]

/** @var DateTime */
$x = new DateTime();
$x-> (on this point fails)

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /home/roderick/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:94

TypeError: Cannot read property '1' of null
  at Object.module.exports.findUseForClass (/home/roderick/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:94:12)
  at Object.module.exports.getVariableType (/home/roderick/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:317:19)
  at Object.module.exports.parseElements (/home/roderick/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:363:24)
  at AutocompleteProvider.module.exports.AutocompleteProvider.fetchSuggestions (/home/roderick/.atom/packages/atom-autocomplete-php/lib/providers/autocomplete-provider.coffee:29:24)
  at AutocompleteProvider.module.exports.AbstractProvider.getSuggestions (/home/roderick/.atom/packages/atom-autocomplete-php/lib/providers/abstract-provider.coffee:23:13)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at atom-text-editor.subscriptions.add.atom.commands.add.autocomplete-plus:activate (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:197:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:15.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:14.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:35.1.0 core:copy (atom-text-editor.editor.is-focused)
     -2:30.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:28 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:59.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:58.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:45.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:43.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:18.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:17.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:17 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:11 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:09.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-introspector",
      "atom-phpcs",
      "atom-beautify",
      "doctrine",
      "delorean",
      "autocomplete-php"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "/home/roderick/Developer/composer.phar",
    "binPhp": "/usr/bin/php"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.5.0
local-history, v3.2.3
php-twig, v4.0.0
symfony-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment] 2015-07-22 17:19
Hello,

The code you given don't fail when I test it.
Could you please tell me what do you have on top of your files ? (namespace ? uses ? etc...) before your class declaration.

Regards,
Peekmo

**Comment by rdcklinux** [comment] 2015-07-24 18:54
this is a simple Symfony Controller, in any Action function whitout code inside

**Comment by Peekmo** [comment] 2015-08-02 10:00
If you could copy/past the method declaration and the namespace/uses on top of file, it would be fine :+1: 

If you don't have the problem anymore, you can also close this issue.

Regards,
Peekmo

**Comment by Peekmo** [comment] 2015-09-01 06:15
No answers so.. I close this issue. Feel free to open a new one.

Regards,
Peekmo

**Comment by MarjoDebote** [comment] 2015-10-06 14:08
Hi,
First time commenting an issue, I just followed the "View Issue" link.

I am writing in a drupal feature, I was at the top of a .inc file and wrote this :
```
<?php
/**
 * @file
 * some text
 */
 use
/**
 * Implements hook_conditional_fields_default_fields().
 */
function arrivant_conditional_fields_default_fields() {
```

Every time I write 'use' on top of a .inc file, this error is called. It's not like I was going to use it but still.

**Comment by Peekmo** [comment] 2015-10-06 14:13
Hi,

thank you for the informations.
The issue is probably not the same (because the code as widely changed since Jul 22), but I will take a look.

Regards,
Peekmo

**Comment by MarjoDebote** [comment] 2015-10-07 07:19
Sure, tell me if you need any extrinformation

**Comment by XT-19** [comment] 2015-10-07 10:54
I've got the same problem as Marjo as soon as I type use for namespaces I get the error message.

**Comment by JoelESvensson** [comment] 2015-10-07 14:34
I also have this problem. I happened when saving a file that had an incomplete use statement

**Comment by MarjoDebote** [comment] 2015-10-09 14:07
Tried to write 'use' in a .inc file today, everything is working fine. Seems like you fixed the issue.
Congrats !

**Comment by hotoiledgoblinsack** [comment] 2015-10-09 14:47
Yes, I had noticed this as well. It was driving me mad as I kept getting spammed with errors while trying to write a use statement. When I got around to actually debugging it, I couldn't reproduce it anymore, must have been one of the other changes I did that somehow resolved it as a side effect.

**Closed** 2015-10-09 14:50 UTC
Labels: bug

**Comment by Peekmo** [comment] 2015-10-09 14:53
I close the issue so.

Feel free to reopen it if the error appears again ;)
(I never get this bug, even in an .inc file :()
