### ISSUE TITLE
Autocomplete is not working

### ISSUE THREAD

**Issue by alexandernst** [Peekmo/atom-autocomplete-php#18] opened 2015-06-05 08:03 UTC
I'm on Debian Linux, Atom .206. I'm currently working on a project which uses composer, but I don't see any autocomplete at all.

I opened dev tools to check if the plugin was crashing behind the scene, but it's not. I do see a `Building index` and `Build done` messages in the console, but I don't see any autocomplete.

**Comment by Peekmo** [comment] 2015-06-05 08:03
The plugin seems to not work well with the last version of atom.

Use atom --include-deprecated-apis to use it. I don't know why because I haven't got deprecations on the plugin. So, I need to learn more about changes.

**Comment by alexandernst** [comment] 2015-06-05 08:06
Even with `--include-deprecated-apis` it's not working at all. Is it working for you on .206 with that argument?

**Comment by Peekmo** [comment] 2015-06-05 08:07
Yes, it works with this argument.

What are you trying to achieve ? Is it a project manage with composer ?

**Comment by alexandernst** [comment] 2015-06-05 08:16
Yes,  it's a Yii2 project managed with composer.

I tried the very simplest thing: `$a = new DateTime(); $a->` and it didn't show any autocomplete stuff.

**Comment by Peekmo** [comment] 2015-06-05 08:20
This case is not managed for the moment (not so simple to do ;)). Just class properties and methods are managed. The keyword "$this" so

You should have autocompletion with $this->... ; new ....
You should have namespace wrote if you press ctrl - alt - n.

If that works, the plugin is well installed. Your demand will be implemented later.

**Comment by Peekmo** [comment] 2015-06-05 08:22
You can have a look to [the readme](https://github.com/Peekmo/atom-autocomplete-php#what-is-done-) for more about features.

**Comment by alexandernst** [comment] 2015-06-05 08:31
I tried with  `$this`, but that isn't working either. I wrote the full path of my composer bin, as well as the php binary. Is there some way to debug your plugin?

**Comment by Peekmo** [comment] 2015-06-05 08:36
You can console.log in [~/.atom/atom-autocomplete-php/lib/services/php-proxy.coffee](https://github.com/Peekmo/atom-autocomplete-php/blob/master/lib/services/php-proxy.coffee#L70) in the catch and after the catch. If it enters in the catch, it's that the composer.json is not found and so, it means that you didn't open atom in the project folder.

If it passes, I don't know where the problem come from.

**Comment by alexandernst** [comment] 2015-06-05 08:46
I put some  console.log, but none of the `catch` paths is executed, so it's not crashing. It just doesn't show any suggestions.

I don't have enough time to debug this properly, so I'll leave the issue open and get back when I have more time ;)

**Comment by Peekmo** [comment] 2015-06-05 08:51
You did a composer install on your project ?
You should have something like that in the root of the directory opened in atom

|- composer.json
|- vendor
----|- autoload.php

**Comment by alexandernst** [comment] 2015-06-05 09:04
Yes, I have only 1 folder opened, and yes, the project is managed with composer.

**Comment by Peekmo** [comment] 2015-06-05 09:09
Ok, so I really don't know.

I will test 0.206.0 on linux this evening to be sure that it's not a problem with the version. I'll try to find the problem that occurs when "--include-deprecated-apis " is not set. Perhaps the problem is the same for linux. (I'm on OSX now)

**Comment by Peekmo** [comment] 2015-06-05 10:12
It works well without --include-deprecated-apis on OSX finally.

So I have no idea for your problem :(

**Comment by harikt** [comment] 2015-06-25 17:21
I am also having some issues. Not sure whether this is related.

This is what I copied from the error reported.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.1
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.1.4


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/hari/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:22

TypeError: undefined is not a function
  at Object.module.exports.createNamespace (/home/hari/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:22:19)
  at atom-workspace.atom.commands.add.atom-autocomplete-php:namespace (/home/hari/.atom/packages/atom-autocomplete-php/lib/config.coffee:43:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -2:17.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:05.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:03.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:02.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:00.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -1:57.7.0 atom-autocomplete-php:namespace (atom-text-editor.editor.is-focused)
     -1:55.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:55.3.0 core:delete (atom-text-editor.editor.is-focused)
     -1:55.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:54.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:54.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.6.0 command-palette:toggle (table.package-keymap-table.table.native-key-bindings.text)
     -0:06.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 atom-autocomplete-php:namespace (table.package-keymap-table.table.native-key-bindings.text)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "/usr/bin/composer"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.1.4
language-php, v0.22.0
php-twig, v4.0.0
tabs-to-spaces, v0.9.0

# Dev
No dev packages
```

**Comment by harikt** [comment] 2015-06-25 17:23
By the way I am having two folders opened.

**Comment by Peekmo** [comment] 2015-06-25 17:52
Hello,

Thanks for the report. In fact, I don't warranty that it works with 2 folders opened. Really harder and not a priority for the moment sorry.

I use atom with multiple windows for multiple projects for the moment.

**Comment by harikt** [comment] 2015-06-25 17:55
sure, no problem @Peekmo .

Thank you for the quick response, and thanks for this wonderful piece of software.

Enjoy your day.

**Comment by Peekmo** [comment] 2015-06-25 17:55
No problem, I'll try to improve it again soon ;)

Regards,
Peekmo

**Comment by meigallodixital** [comment] 2015-07-01 22:28
I have not any autocomplete. For test this  I installed a clean installation of symfony 2.7 and will not work either.

Im on windows 7, atom 1.0 and last version of autocomplete.

**Comment by Peekmo** [comment] 2015-07-02 04:43
Hello.

- What is your test for autocompletion ?
- Your vendors are installed ?
- If you opened your project before `compoer install`, did you reload atom ?

Regards,
Peekmo

**Comment by meigallodixital** [comment] 2015-07-02 10:35
* I tried both with $this as new instance ... own classes or symfony ones
* Yes
* Yes

**Comment by Peekmo** [comment] 2015-07-02 12:11
Did you open the whole project directory ? (and only this one) in atom ?

I'll try it on windows.

**Comment by meigallodixital** [comment] 2015-07-02 16:06
Yes, a clean symfony install to have a clean test scenario.

**Comment by alexandernst** [comment] 2015-07-02 16:37
@Peekmo I'd suggest looking for any Mac OS specific code you could have written as this doesn't work neither on Windows nor in Linux. Can't help any further though, got 0 spare time right now :(

**Comment by harikt** [comment] 2015-07-02 16:40
> you could have written as this doesn't work neither on Windows nor in
Linux

It is actually working on Linux. I confirm.

Only issue is when you have more than 1 project.

**Comment by alexandernst** [comment] 2015-07-02 16:42
Oh, so we're looking at a heisen bug then. Did you do anything special to get it working? What theme are you using? What other plugins? What config?

**Comment by harikt** [comment] 2015-07-02 16:49
@alexandernst I hope [https://github.com/Peekmo/atom-autocomplete-php/issues/18#issuecomment-115330480](this comment) is what you are looking for.

**Comment by Peekmo** [comment] 2015-07-02 20:20
Linux and MacOS are working because the command line is very similar.

I'm not sure that it works well on Windows.

@meigallodixital Did you take a look to the plugin settings ? PHP and Composer options are the most important. I have a task (#30) to make a command to test the configuration.

**Comment by meigallodixital** [comment] 2015-07-03 08:35
![autocomplete](https://cloud.githubusercontent.com/assets/2930599/8495603/1948383a-216f-11e5-8c08-b991e2c153f8.png)

Autoload and classmap file is on default path.

**Comment by meigallodixital** [comment] 2015-07-09 11:07
With the new version if I delete composer.json gives error on develop tools. 

If I keep it then works and build returns done. But still no auto or with $this or self:: or generating an new object.

**Comment by Peekmo** [comment] 2015-07-09 11:31
Hello,

I need to completly test it on windows. I can't debug without the OS and PHP on it. I'll try to work on, but I never worked on this platform, so that's hard.

If you know how PHP works on windows, you're welcome to help me to make the plugin works (I can give you all the informations on where to look on, there's not so many places. It's probably on the execution of a php command that something fail).

Note that it's normal that you have an error if you delete the composer.json.

**Comment by meigallodixital** [comment] 2015-07-09 11:40
No problem. 

If you explain to me where and how to debug the plugin I try to see where it might be failing .

**Comment by Peekmo** [comment] 2015-07-09 12:27
[In this coffee file](https://github.com/Peekmo/atom-autocomplete-php/blob/master/lib/services/php-proxy.coffee#L24) is where almost all the commands are executed from atom (there is command exec from php files too, but if you can debug the first one, the ). When you type $this-> this line is executed. So you can console.log the command and try to execute it directly from your command line (from the plugin directory. I don't know where atom store its plugins on windows, but on linux/OSX it's in ~/.atom/packages)

Perhaps do you will see the problem with this command on windows ?

You can join me on the [project chatroom](https://gitter.im/Peekmo/atom-autocomplete-php?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions

**Comment by Peekmo** [comment] 2015-08-03 07:07
I'm closing this issue.

The project has changed a lot since its opening date. So, if anyone have a problem again, open a new one please.

Regards,
Peekmo

**Closed by Peekmo** 2015-08-03 07:07 UTC
