### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by redimongo** [Peekmo/atom-autocomplete-php#304] opened 2016-11-17 20:32 UTC
1. .. create a class function using latest mongodb php driver (not mongo driver php) inside that this code static public $_db;
	public static function db()
	{
   	 if (!static::$_db) {
			 if(CLUSTER !=null){
					static::$_db = new MongoDB\Client("mongodb://".SITEDBUSERNAME.":".SITEDBPASS."@".SITEDBURL.":27017/".SITEDB);
				}else{
					static::$_db = new MongoDB\Client("mongodb://".SITEDBUSERNAME.":".SITEDBPASS."@".SITEDBURL.",".CLusteroption);
				}
		 }

		 $siteDB = SITEDB;
   	 return static::$_db->$siteDB;

	}

**Atom Version**: 1.12.3
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.2
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.20.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Frussellharrower%2FSites%2Fipet%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Frussellharrower%2FSites%2Fipet%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F37%2Fgzk1h8dd58s39xdm996ks67h0000gn%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0xF%22%2C%22HOME%22%3A%22%2FUsers%2Frussellharrower%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.R54t6OizYx%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.l8ii3j2Q4N%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22russellharrower%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.14356%22%2C%22USER%22%3A%22russellharrower%22%2C%22SECURITYSESSIONID%22%3A%22186a6%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Frussellharrower%2F.atom%22%7D%2C%22appVersion%22%3A%221.12.3%22%2C%22atomHome%22%3A%22%2FUsers%2Frussellharrower%2F.atom%22%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at ChildProcess.<anonymous> (/Users/russellharrower/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:83:52)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

### Commands

```
     -4:00.5.0 core:move-right (atom-text-editor.editor.is-focused)
  9x -4:00.0 core:select-right (atom-text-editor.editor.is-focused)
     -3:57.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:56 core:save (atom-text-editor.editor.is-focused)
     -0:09.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:06.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "insertNewlinesForUseStatements": true,
    "verboseErrors": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.20.2 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.6 (active)
atom-typescript, v10.1.12 (active)
auto-detect-indentation, v1.3.0 (active)
autoclose-html, v0.23.0 (active)
linter, v1.11.18 (active)
mdl-snippets, v0.3.0 (inactive)
Remote-FTP, v0.9.4 (active)
todo-show, v1.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by amraei** [comment] 2017-01-01 17:00
This bug is very annoying

**Comment by achton** [comment] 2017-01-02 09:55
This is a duplicate of #303.

**Comment by Peekmo** [comment] 2017-01-11 08:40
Hello,

Should be fixed.

**Closed by Peekmo** 2017-01-11 08:40 UTC
